title: Home Server
description: Home server
theme: dark
color: slate
headerStyle: clean
statusStyle: dot
target: _self
hideVersion: true
cardBlur: md
iconStyle: gradient
useEqualHeights: true
layout:
  Live:
    style: row
    columns: 1
    icon: mdi-pulse
  Media:
    style: row
    columns: 2
    icon: mdi-play-circle-outline
  Home:
    style: row
    columns: 2
    icon: mdi-home-lightbulb-outline
  Tools:
    style: row
    columns: 2
    icon: mdi-wrench-outline
  Background:
    style: row
    columns: 2
    icon: mdi-server-outline
    initiallyCollapsed: true
