- datetime:
    text_size: xl
    format:
      timeStyle: short
      hour12: true

- resources:
    cpu: true
    cputemp: true
    memory: true
    uptime: true
    disk: /mnt/host-root
    units: metric
    tempmin: 30
    tempmax: 90
